// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: intros.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc-gen-objc which is incompatible with your Protocol Buffer sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - BNIIntrosRoot

@interface BNIIntrosRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - BNIUser

typedef GPB_ENUM(BNIUser_FieldNumber) {
  BNIUser_FieldNumber_FirstName = 1,
  BNIUser_FieldNumber_LastName = 2,
  BNIUser_FieldNumber_PhoneNumber = 3,
  BNIUser_FieldNumber_Facebook = 4,
  BNIUser_FieldNumber_Snapchat = 5,
  BNIUser_FieldNumber_Twitter = 6,
};

@interface BNIUser : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *firstName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *lastName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *phoneNumber;

@property(nonatomic, readwrite, copy, null_resettable) NSString *facebook;

@property(nonatomic, readwrite, copy, null_resettable) NSString *snapchat;

@property(nonatomic, readwrite, copy, null_resettable) NSString *twitter;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
