// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: intros.proto

#import "GPBProtocolBuffers_RuntimeSupport.h"
#import "Intros.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma mark - BNIIntrosRoot

@implementation BNIIntrosRoot

@end

#pragma mark - BNIIntrosRoot_FileDescriptor

static GPBFileDescriptor *BNIIntrosRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - BNIUser

@implementation BNIUser

@dynamic firstName;
@dynamic lastName;
@dynamic phoneNumber;
@dynamic facebook;
@dynamic snapchat;
@dynamic twitter;

typedef struct BNIUser__storage_ {
  uint32_t _has_storage_[1];
  NSString *firstName;
  NSString *lastName;
  NSString *phoneNumber;
  NSString *facebook;
  NSString *snapchat;
  NSString *twitter;
} BNIUser__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "firstName",
        .number = BNIUser_FieldNumber_FirstName,
        .hasIndex = 0,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
        .offset = offsetof(BNIUser__storage_, firstName),
        .defaultValue.valueString = nil,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "lastName",
        .number = BNIUser_FieldNumber_LastName,
        .hasIndex = 1,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
        .offset = offsetof(BNIUser__storage_, lastName),
        .defaultValue.valueString = nil,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "phoneNumber",
        .number = BNIUser_FieldNumber_PhoneNumber,
        .hasIndex = 2,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
        .offset = offsetof(BNIUser__storage_, phoneNumber),
        .defaultValue.valueString = nil,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "facebook",
        .number = BNIUser_FieldNumber_Facebook,
        .hasIndex = 3,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
        .offset = offsetof(BNIUser__storage_, facebook),
        .defaultValue.valueString = nil,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "snapchat",
        .number = BNIUser_FieldNumber_Snapchat,
        .hasIndex = 4,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
        .offset = offsetof(BNIUser__storage_, snapchat),
        .defaultValue.valueString = nil,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
      {
        .name = "twitter",
        .number = BNIUser_FieldNumber_Twitter,
        .hasIndex = 5,
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
        .offset = offsetof(BNIUser__storage_, twitter),
        .defaultValue.valueString = nil,
        .dataTypeSpecific.className = NULL,
        .fieldOptions = NULL,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[BNIUser class]
                                     rootClass:[BNIIntrosRoot class]
                                          file:BNIIntrosRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:sizeof(fields) / sizeof(GPBMessageFieldDescription)
                                        oneofs:NULL
                                    oneofCount:0
                                         enums:NULL
                                     enumCount:0
                                        ranges:NULL
                                    rangeCount:0
                                   storageSize:sizeof(BNIUser__storage_)
                                    wireFormat:NO];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


// @@protoc_insertion_point(global_scope)
